In [1]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_csv('Pfizer_1.csv')

In [26]:
data.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       18 non-null     object
 1   Drug_Name  18 non-null     object
 2   Parameter  18 non-null     object
 3   1:30:00    16 non-null     float64
 4   2:30:00    16 non-null     float64
 5   3:30:00    12 non-null     float64
 6   4:30:00    14 non-null     float64
 7   5:30:00    16 non-null     float64
 8   6:30:00    18 non-null     int64
 9   7:30:00    16 non-null     float64
 10  8:30:00    14 non-null     float64
 11  9:30:00    16 non-null     float64
 12  10:30:00   18 non-null     int64
 13  11:30:00   16 non-null     float64
 14  12:30:00   18 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 2.2+ KB

In [8]:
data.Parameter.unique()

array(['Temperature', 'Pressure'], dtype=object)

In [27]:
data_melt = pd.melt(data, id_vars = ['Date', 'Drug_Name', 'Parameter'], 
              var_name='time',
              value_name='reading')

In [28]:
data_melt.head(20)

          Date                Drug_Name    Parameter     time  reading
0   15-10-2020  diltiazem hydrochloride  Temperature  1:30:00     23.0
1   15-10-2020  diltiazem hydrochloride     Pressure  1:30:00     12.0
2   15-10-2020      docetaxel injection  Temperature  1:30:00      NaN
3   15-10-2020      docetaxel injection     Pressure  1:30:00      NaN
4   15-10-2020   ketamine hydrochloride  Temperature  1:30:00     24.0
5   15-10-2020   ketamine hydrochloride     Pressure  1:30:00      8.0
6   16-10-2020  diltiazem hydrochloride  Temperature  1:30:00     34.0
7   16-10-2020  diltiazem hydrochloride     Pressure  1:30:00     18.0
8   16-10-2020      docetaxel injection  Temperature  1:30:00     46.0
9   16-10-2020      docetaxel injection     Pressure  1:30:00     23.0
10  16-10-2020   ketamine hydrochloride  Temperature  1:30:00      8.0
11  16-10-2020   ketamine hydrochloride     Pressure  1:30:00     12.0
12  17-10-2020  diltiazem hydrochloride  Temperature  1:30:00     20.0
13  17-10-2020  diltiazem hydrochloride     Pressure  1:30:00      3.0
14  17-10-2020      docetaxel injection  Temperature  1:30:00     12.0
15  17-10-2020      docetaxel injection     Pressure  1:30:00     20.0
16  17-10-2020   ketamine hydrochloride  Temperature  1:30:00     13.0
17  17-10-2020   ketamine hydrochloride     Pressure  1:30:00      8.0
18  15-10-2020  diltiazem hydrochloride  Temperature  2:30:00     22.0
19  15-10-2020  diltiazem hydrochloride     Pressure  2:30:00     13.0

In [34]:
data_melt.pivot(index=['Date', 'Drug_Name', 'Parameter'], columns='time', values='reading').reset_index().head(3)

time,Date,Drug_Name,Parameter,10:30:00,11:30:00,12:30:00,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00
0,15-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,12.0,13.0,NaN,11.0,13.0,14.0,16.0,16.0,24.0
1,15-10-2020,diltiazem hydrochloride,Temperature,20.0,20.0,21.0,23.0,22.0,NaN,21.0,21.0,22.0,23.0,21.0,22.0
2,15-10-2020,docetaxel injection,Pressure,26.0,29.0,28.0,NaN,22.0,22.0,NaN,22.0,23.0,NaN,NaN,27.0

In [40]:
data_pivoted = data_melt.pivot(index=['Drug_Name', 'Date', 'time'], columns=['Parameter'] , values='reading').reset_index()

In [42]:
data_pivoted.head()

Parameter,Drug_Name,Date,time,Pressure,Temperature
0,diltiazem hydrochloride,15-10-2020,10:30:00,18.0,20.0
1,diltiazem hydrochloride,15-10-2020,11:30:00,19.0,20.0
2,diltiazem hydrochloride,15-10-2020,12:30:00,20.0,21.0
3,diltiazem hydrochloride,15-10-2020,1:30:00,12.0,23.0
4,diltiazem hydrochloride,15-10-2020,2:30:00,13.0,22.0

# Handling missing values

In [44]:
data_pivoted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Drug_Name    108 non-null    object
 1   Date         108 non-null    object
 2   time         108 non-null    object
 3   Pressure     95 non-null     float64
 4   Temperature  95 non-null     float64
dtypes: float64(2), object(3)
memory usage: 4.3+ KB

In [49]:
type(np.NaN)

float

In [55]:
np.array([1,2, np.nan, None]).dtype

dtype('O')

In [62]:
a = pd.Series(["1", "np.nan", np.nan])

In [71]:
data.isnull()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
5,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [75]:
data.dropna()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [74]:
data.dropna().shape

(4, 15)

In [76]:
data.dropna(axis=1)

,Date,Drug_Name,Parameter,6:30:00,10:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,22,20,21
1,15-10-2020,diltiazem hydrochloride,Pressure,14,18,20
2,15-10-2020,docetaxel injection,Temperature,18,23,25
3,15-10-2020,docetaxel injection,Pressure,23,26,28
4,15-10-2020,ketamine hydrochloride,Temperature,26,22,20
5,15-10-2020,ketamine hydrochloride,Pressure,9,9,11
6,16-10-2020,diltiazem hydrochloride,Temperature,38,40,42
7,16-10-2020,diltiazem hydrochloride,Pressure,23,24,27
8,16-10-2020,docetaxel injection,Temperature,49,56,58
9,16-10-2020,docetaxel injection,Pressure,27,28,30
10,16-10-2020,ketamine hydrochloride,Temperature,12,13,15
11,16-10-2020,ketamine hydrochloride,Pressure,15,16,18
12,17-10-2020,diltiazem hydrochloride,Temperature,16,14,10
13,17-10-2020,diltiazem hydrochloride,Pressure,8,11,14
14,17-10-2020,docetaxel injection,Temperature,17,21,23
15,17-10-2020,docetaxel injection,Pressure,23,28,28
16,17-10-2020,ketamine hydrochloride,Temperature,18,22,24
17,17-10-2020,ketamine hydrochloride,Pressure,12,13,15

In [77]:
data.dropna(axis=1).shape

(18, 6)

In [84]:
data['1:30:00'].fillna(-1, inplace=True)

In [92]:
data.fillna(data.mean())

/var/folders/sg/qf1dw3cs4q5007gb2_9zd8600000gr/T/ipykernel_90205/3231489778.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.fillna(data.mean())

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0000,16.916667,21.000000,21.0000,22,23.000,21.000000,22.000,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0000,16.916667,11.000000,13.0000,14,16.000,16.000000,24.000,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,-1.0,17.0000,18.000000,20.142857,17.0000,18,21.125,22.714286,23.000,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,-1.0,22.0000,22.000000,20.142857,22.0000,23,21.125,22.714286,27.000,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,18.8125,16.916667,27.000000,20.0625,26,25.000,24.000000,23.000,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,18.8125,16.916667,7.000000,20.0625,9,10.000,11.000000,10.000,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0000,36.000000,36.000000,37.0000,38,37.000,38.000000,39.000,40,22.0,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0000,20.000000,21.000000,22.0000,23,24.000,25.000000,25.000,24,22.0,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0000,16.916667,48.000000,48.0000,49,50.000,52.000000,55.000,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0000,16.916667,25.000000,26.0000,27,28.000,29.000000,28.000,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0000,10.000000,20.142857,11.0000,12,12.000,11.000000,23.625,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0000,13.000000,20.142857,15.0000,15,15.000,15.000000,23.625,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0000,19.000000,18.000000,17.0000,16,15.000,22.714286,13.000,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0000,4.000000,4.000000,6.0000,8,9.000,22.714286,9.000,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0000,14.000000,15.000000,16.0000,17,18.000,19.000000,20.000,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0000,22.000000,22.000000,22.0000,23,25.000,26.000000,27.000,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0000,15.000000,16.000000,17.0000,18,19.000,20.000000,21.000,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0000,10.000000,11.000000,11.0000,12,12.000,11.000000,12.000,13,14.0,15

In [98]:
data

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,-1.0,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,-1.0,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [99]:
df = pd.DataFrame({
  "Accessories": ["Laptop", "Laptop", "Ipad", "Ipad", "Tablet", "Laptop"],
  "customer": ["Andrew", "Andrew", "Tom", "Andrew", "Tobey", "Peter"],
  "quantity": [1, 2, 2, 3, 1, 2],
})

In [100]:
df

  Accessories customer  quantity
0      Laptop   Andrew         1
1      Laptop   Andrew         2
2        Ipad      Tom         2
3        Ipad   Andrew         3
4      Tablet    Tobey         1
5      Laptop    Peter         2

In [103]:
# df.pivot(index=['Accessories', 'customer'],columns='customer', values='quantity')

In [114]:
df.groupby(['Accessories', 'customer']).sum()

                      quantity
Accessories customer
Ipad        Andrew           3
            Tom              2
Laptop      Andrew           3
            Peter            2
Tablet      Tobey            1

In [116]:
df.set_index(["Accessories", "customer"])["quantity"]

Accessories  customer
Laptop       Andrew      1
             Andrew      2
Ipad         Tom         2
             Andrew      3
Tablet       Tobey       1
Laptop       Peter       2
Name: quantity, dtype: int64

In [118]:
df.groupby(['Accessories', 'customer']).quantity.sum()

Accessories  customer
Ipad         Andrew      3
             Tom         2
Laptop       Andrew      3
             Peter       2
Tablet       Tobey       1
Name: quantity, dtype: int64

In [119]:
data

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,-1.0,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,-1.0,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [120]:
data.isnull().any(axis=1)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14    False
15    False
16    False
17    False
dtype: bool

In [125]:
def is_null(x): 
        return sum(x.isnull())

In [126]:
data.apply(is_null, axis=1)

0     1
1     1
2     3
3     3
4     3
5     3
6     1
7     1
8     1
9     1
10    2
11    2
12    1
13    1
14    0
15    0
16    0
17    0
dtype: int64

In [127]:
data

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,-1.0,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,-1.0,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15